[env:esp32dev]
platform = espressif32 @ 6.6.0
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -O2

lib_deps = 
    lovyan03/LovyanGFX @ ^1.1.16
    mikalhart/TinyGPSPlus @ ^1.1.0
